language: java

dist: trusty

jdk:
- openjdk8

branches:
  except:
  - new-branch

before_install:
- mvn clean

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn clean package -Pproduction heroku:deploy